name: ysdistributors.com
favicon: null
layout_spectrum: 0.6129025940317661
typography_spectrum: 0.6415908085182309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9696709115523845
  lightness: 0.24595686770044267
  saturation: 0.8610490588471293
  rhythmicContrast: 0.5865544765256345
purpose: []
